name: Plex Scraper Workflow

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Plex scraper
        run: python plex_scraper.py

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          if ls *_*.m3u *_*.xml >/dev/null 2>&1; then
            git add *_*.m3u *_*.xml
            git commit -m "Update Plex M3U and EPG - $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No M3U or XML files found to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
