name: Plex Scraper Workflow

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Run the scraper
      - name: Run Plex scraper
        env:
          PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}
        run: python plex_scraper.py

      # Commit and push results
      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          if ls *_*.json >/dev/null 2>&1; then
            git add *_*.json
            git commit -m "Update Plex scraper data - $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No JSON files found to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
